config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :conversations do
    resources :messages
  end
  get 'fetch/:conversation_id/messages', to: 'messages#messages_index', as: 'get_messages'

  resources :follows, only: %i[create destroy]
  resources :module_types, only: [:index]
  resources :database_tables
  resources :feeds
  resources :members
  post '/auth/login', to: 'authentication#login'
  get '/auth/verify', to: 'authentication#verify'

  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  root 'posts#index'
  get 'pages/about', as: 'pages_about'
  get 'pages/innovation', as: 'pages_innovation'
  get 'pages/help', as: 'pages_help'
  get 'pages/success'
  get 'pages/terms', as: 'pages_terms'
  get 'pages/privacy', as: 'pages_privacy'

  devise_for :users,
             path: '',
             path_name: { sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration' },
             controllers: { registrations: 'registrations' }

  resources :users, only: %i[index show] do
    resource :follows, only: %i[create destroy], shallow: true
  end

  resource :contact_tables, only: [:create]
  resources :columns_for_fake_databases

  resources :posts, param: :slug, only: %i[index show update create destroy] do
    resources :photos, only: [:create]
    resources :likes, only: %i[create destroy], shallow: true
    resources :comments, only: %i[index create destroy], shallow: true
    resources :bookmarks, only: %i[create destroy], shallow: true
  end

  # custom route defined
  get 'notifications', to: 'notifications#index', as: 'get_notification'
  # get 'pages/contact_get'

  get 'pages/howto', to: 'pages#howto', as: 'how_to'
  get 'users/likes/:id', to: 'users#likes', as: 'users_likes'
  get 'users/bookmark/:id', to: 'users#bookmark', as: 'users_bookmark'
  get 'pages/contact_get', as: 'contact'
  post 'pages/contact_get/:id', to: 'pages#contact_get'
  get 'post/module_post', to: 'posts#module_post', as: 'module'
  get 'posts/build_module/:slug', to: 'posts#build_module', as: 'building'
  # get 'pages/userlandingtesting', :to => 'pages#userlandingtesting', as: 'landingtesting'

  # For Backend module
  get 'backends/backend_module'
  post 'backends/backend_module_post', to: 'backends#backend_module_post'

  mount ActionCable.server, at: '/cable'
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :post
end

app/models/code_file.rb
class CodeFile < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many_attached :files

  after_create :add_fileid

  def add_fileid
    random = UUID.new
    file_id = random.generate
    self.fileid = file_id
    save!
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/data_type.rb
class DataType < ApplicationRecord
  belongs_to :columns_for_fake_database, class_name: 'ColumnsForFakeDatabase', foreign_key: 'columns_id'
end

app/models/fake_like.rb
class FakeLike < ModuleRecord
end

app/models/fake_post.rb
class FakePost < ModuleRecord
end

app/models/fake_user.rb
class FakeUser < ModuleRecord
end

app/models/feed.rb
class Feed < ApplicationRecord
  belongs_to :user, foreign_key: :user_id, class_name: 'User'
  belongs_to :post, foreign_key: :post_id, class_name: 'Post'
  belongs_to :feedable, polymorphic: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: :follower_id, class_name: 'User'
  belongs_to :following, foreign_key: :following_id, class_name: 'User'
end

app/models/import.rb
class Import < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/member.rb
class Member < ApplicationRecord
  has_secure_password

  has_many :posts
  has_many :likes
  has_many :comments
  has_many :bookmarks
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

  scope :new_messages, -> { where('created_at > ?', 1.day.ago) }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  validates :image, presence: true

  mount_uploader :image, PhotoUploader
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId

  belongs_to :user

  friendly_id :content, use: %i[slugged finders]

  # Validations
  # validates :content, presence: true
  # validates :frontend, presence: true
  # validates :frontend_css, presence: true

  with_options dependent: :destroy do |post|
    post.has_many :photos
    post.has_many :likes, -> { order(created_at: :desc) }
    post.has_many :comments, -> { order(created_at: :desc) }
    post.has_many :bookmarks
    post.has_many :languages
    post.has_many :tags
    post.has_many :categories
    post.has_many :notifications
    post.has_many :code_files
  end

  has_one :image_repo

  accepts_nested_attributes_for :code_files
  before_create :post_published

  # Backend implementation
  # has_many :columns_for_fake_databases
  # through: :database_tables if self.module_type == "1"

  scope :new_posts, -> { where('created_at > ?', 1.week.ago) }
  scope :published, -> { where(published: true) }

  # def module_type post
  #   if post.module_type == "1"
  #     puts "BACKEND"
  #   elsif post.module_type == "2"
  #     puts "FRONTEND"
  #   else
  #     puts "Something went wrong"
  #   end
  # end

  def is_belongs_to?(user)
    Post.find_by(user_id: user.id, id:)
  end

  def is_liked(user)
    return unless user

    Like.find_by(user_id: user.id, post_id: id)
  end

  def is_bookmarked(user)
    return unless user

    Bookmark.find_by(user_id: user.id, post_id: id)
  end

  def self.search(term)
    return unless term

    where('content LIKE ?', "%#{term}%")
  end

  def post_published
    self.published = true
  end
end

app/models/stat.rb
class Stat < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  has_many :code_files
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments
  has_many :bookmarks
  has_many :follows, foreign_key: :follower_id, class_name: 'Follow'

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true

  def is_followed(user)
    Follow.find_by(follower_id: user.id, following_id: id)
  end

  def self.search(term)
    return unless term

    where('content LIKE ?', "%#{term}%")
  end
end

app/views/exception/show.html.erb
<h1>404 error</h1>

app/views/shared/_devisemes.html.erb
<% if resource.errors.any? %>
 <script type="text/javascipt">
    <% resource.errors.full_messages.each do |value| %>
        toastr.error('<%= value %>')
    <% end %>
 </script>
<% end %>

app/views/shared/_footer.html.erb
<br>
<br>
<br>
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-bottom">
   <div class="footer-logo">
    <b><p>OpenSnip</p></b>
   <div>    
</nav>

app/views/shared/_frontfooter.html.erb
<!--Footer start-->
<section id="footer" class="section footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-12">
              <div class="footer-logo">
                 <a href="#">OpenSnip</a>
              </div>
              <div class="contact-info">
                 <p>
                    Speed up your development with high quality modules. 
                 </p>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-12">
               <div class="single-footer f-link">
                    <h5>Quick menu</h5>
                    <ul>
                        <li><%= link_to "About Us", pages_about_path %></li>
                        <li><%= link_to "Terms", pages_terms_path %></li>
                        <li><%= link_to "Privacy", pages_privacy_path %></li> 
                        <li><a href="#">Services</a></li>
                        <li><%= link_to "Contact us", contact_path %></li> 

                        <!--<li><a href="#">Contact us</a></li>-->
                    </ul>
               </div>
            </div>
            <div class="col-lg-3 col-md-3 col-12">
                <div class="single-footer f-link">
                  <h5>Featured links</h5>
                    <ul>
                    <li><%= link_to "Documentation", pages_help_path, :class => "nav-item" %></li>     
                        <li class="nav-item"><a href="#">Search For Modules</a></li>
                        <li class="nav-item"><a href="#">Blog</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-12">
                <div class="single-footer f-contact">
                  <h5>Keep in touch</h5>
                  <div class="contact-info">
                     <p>
                      Need help to develop your software contact
                    </p>
                  </div>
                  <p>
                     <a href="mailto:pradeep.rao@londevs.com">pradeep.rao@londevs.com</a>
                  </p>
                    <ul class="footer-social">
                        <li><a href="https://www.facebook.com/LonDevs-108128748163900"><i class="lni lni-facebook-filled"></i></a></li>
                        <li><a href="https://www.instagram.com/londevscom/"><i class="lni lni-instagram-original"></i></a></li>
                        <li><a href="https://www.linkedin.com/company/londev"><i class="lni lni-linkedin-original"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <p class="text-center copyright">2023 OpenSnip</p>
            </div>
        </div>
    </div>
</section>
<!--Footer end-->

app/views/shared/_frontnavbar.html.erb
<!-- Preloader -->
<div class="preeloader">
    <div class="preloader-spinner"></div>
</div>
<!-- End Preloader -->

<!-- Londevs.com Color Plate -->
<!-- <div class="color-plate ">
    <a class="color-plate-icon"><i class="fa fa-cog fa-spin"></i></a>
    <h4>Londevs.com Colors</h4>
    <p>Speed up your development with high quality modules.</p>
    <span class="color1"></span>
    <span class="color2"></span>
    <span class="color3"></span>
    <span class="color4"></span>
</div> -->
<!-- /End Color Plate -->

<!-- Header Area -->
<header id="site-header" class="site-header">
    <div class="topbar">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-12">
                    <p>Welcome to Londevs.com</p>
                </div>
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="social-contact">
                        <ul>
                            <li><a href="#"><i class="lni lni-facebook-filled"></i></a></li>
                            <li><a href="#"><i class="lni lni-twitter"></i></a></li>
                            <li><a href="#"><i class="lni lni-linkedin-original"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header Bottom -->
    <div class="header-bottom">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-12">
                    <!-- Logo -->
                    <div class="logo">
                        <a class="navbar-brand" href="/"><h3 class="masthead-brand mb-0">LonDevs.com</h3></a>
                    </div>
                    <!-- End Logo -->
                    <div class="mobile-nav"></div>
                </div>
                <div class="col-lg-10 col-md-10 col-12">
                    <!-- Main Menu -->
                    <div class="main-menu">
                        <nav class="navigation">
                            <ul class="nav">
                                <li class="active"><a href="/">Home</a></li>
                                <li><%= link_to "About Us", pages_about_path %></li>
                                <li><%= link_to "Terms", pages_terms_path %></li>
                                <li><%= link_to "Documentation", pages_help_path %></li>                
                            </ul>
                        </nav>
                    </div>
                    <!--/ End Main Menu -->
                    <!--/ End Main Menu -->
                    <%= link_to "Login", new_user_session_path, :class => "button" %>
                    <%= link_to "Register", new_user_registration_path, :class => "button" %>
                </div>
            </div>
        </div>
    </div>
    <!--/ End Header Bottom -->
</header>
<!--/ End Header Area -->

app/views/shared/_navbar.html.erb
<nav class="navbar bg-body-tertiary fixed-top">
    <b><%= link_to "OpenSnip", root_path, :class => "navbar-brand" %></b>
  <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasNavbarLabel">OpenSnip</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
        
      <li class="nav-item">
      <% if params[:controller] == "posts" && params[:action] == "index" %>
        <%= link_to "Modules", root_path, :class => "nav-link active" %>
      <% else %>
        <%= link_to "Modules", root_path, :class => "nav-link" %>
      <% end %>
      </li>

      <li class="nav-item">
      <% if params[:controller] == "posts" && params[:action] == "module_post" %>
        <%= link_to "Frontend", module_path, :class => "nav-link active", :disabled => "disabled" %>
      <% else %>
        <%= link_to "Frontend", module_path, :class => "nav-link", :disabled => "disabled" %>
      <% end %> 
      </li>
        
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.name %>
        </a>
        <ul class="dropdown-menu">
            <% if params[:controller] == "notifications" %>
              <li><%= link_to get_notification_path, :class => "active dropdown-item"  do %>Notification<% end %></li>
            <% else %>
              <li><%= link_to get_notification_path, :class => "dropdown-item"  do %>Notification<% end %></li>
            <% end %>

            <li>
            <% if params[:controller] == "posts" && params[:action] == "module_post" %>
              <%= link_to conversations_path, :class => "dropdown-item active"  do %>Messages<% end %>
            <% else %>
              <%= link_to conversations_path, :class => "dropdown-item"  do %>Messages</span><% end %>
            <% end %>   
            </li>  
          <li><hr class="dropdown-divider"></li>
          <li>
          <%= link_to "Logout", destroy_user_session_path, :class => "dropdown-item" %>
          </li>          
        </ul>
        </li>

      </ul>

      <%= form_tag users_path, method: :get, class: "d-flex mt-3", role: "search", id: "users-search", remote: true do %>
        <%= text_field_tag :term, params[:term], class: "form-control me-2", placeholder: "Search", autocomplete: "off" %>
        <button class="btn btn-outline-success" type="submit">Search</button>
        <div class="row">
        
        </div>
      <% end %>
      <div id="users-result"></div>
    </div>
</div>
</nav>

app/views/shared/_navbarg.html.erb
<!-- navbar starts -->
<nav class="navbar bg-body-tertiary fixed-top">
  <%= link_to "OpenSource", root_path, :class => "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasNavbarLabel">OpenSource</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
        
      <li class="nav-item">
      <% if params[:controller] == "posts" && params[:action] == "index" %>
        <%= link_to "Modules", root_path, :class => "nav-link active" %>
      <% else %>
        <%= link_to "Modules", root_path, :class => "nav-link" %>
      <% end %>
      </li>

      <li class="nav-item">
      <% if params[:controller] == "posts" && params[:action] == "module_post" %>
        <%= link_to "Frontend", module_path, :class => "nav-link active", :disabled => "disabled" %>
      <% else %>
        <%= link_to "Frontend", module_path, :class => "nav-link", :disabled => "disabled" %>
      <% end %> 
      </li>
        
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Signup
        </a>
        <ul class="dropdown-menu">
            <li> 
              <%= link_to "Login", new_user_session_path, :class => "dropdown-item" %>
            </li>
            <li>
              <%= link_to "Register", new_user_registration_path, :class => "dropdown-item" %>
            </li>
        </ul>
      </li>
      </ul>

    </div>
  </div>
</nav>
<!-- nav bar ends -->